name: NBA Daily Prediction

on:
  schedule:
    - cron: '0 1 * * *'   # 每天 UTC 01:00 = 北京时间 09:00
  workflow_dispatch:

jobs:
  run-model:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取代码
        uses: actions/checkout@v3

      - name: 安装 Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 安装依赖
        run: |
          pip install pandas numpy xgboost nba_api joblib

      - name: 进入模型目录
        run: |
          ls
          cd nba_quant_model
          ls

      - name: 训练模型
        run: |
          cd nba_quant_model
          python train.py

      - name: 运行预测
        run: |
          cd nba_quant_model
          python predict_today.py
